export default [

    // ── Texturas ────────────────────────────────────────────────────────────
    {
        name: 'environmentMapTexture',
        type: 'cubeTexture',
        path: [
            '/textures/environmentMap/px.jpg',
            '/textures/environmentMap/nx.jpg',
            '/textures/environmentMap/py.jpg',
            '/textures/environmentMap/ny.jpg',
            '/textures/environmentMap/pz.jpg',
            '/textures/environmentMap/nz.jpg'
        ]
    },
    { name: 'grassColorTexture', type: 'texture', path: '/textures/dirt/color.jpg' },
    { name: 'grassNormalTexture', type: 'texture', path: '/textures/dirt/normal.jpg' },
    { name: 'pinkTexture', type: 'texture', path: '/textures/pinkfloor.jpg' },
    { name: 'texture1', type: 'texture', path: '/textures/textura1.jpg' },
    { name: 'texture3', type: 'texture', path: '/textures/texture3.jpg' },

    // ── Personaje principal ─────────────────────────────────────────────────
    { name: 'foxModel', type: 'gltfModel', path: '/models/Fox/glTF/Fox.gltf' },
    { name: 'girlModel', type: 'fbxModel', path: '/models/girl/Walking.fbx' },
    { name: 'girlIdle', type: 'fbxModel', path: '/models/girl/girkdle.fbx' },

    // ── Elementos de juego ──────────────────────────────────────────────────
    { name: 'coinsModel', type: 'gltfModel', path: '/models/moneda/coin-gold.glb' },
    { name: 'portalModel', type: 'gltfModel', path: '/models/portal/portal_chido.glb' },

    // ── Enemigos ────────────────────────────────────────────────────────────
    { name: 'enemyFastRun', type: 'fbxModel', path: '/models/enemigos/Fast Run.fbx' },
    { name: 'enemyMutantWalking', type: 'fbxModel', path: '/models/enemigos/Mutant Walking.fbx' },
    { name: 'enemyWalk', type: 'fbxModel', path: '/models/enemigos/Walk.fbx' },
    { name: 'enemyWalking', type: 'fbxModel', path: '/models/enemigos/Walking.fbx' },
    { name: 'enemyWheelbarrowWalk', type: 'fbxModel', path: '/models/enemigos/Wheelbarrow Walk.fbx' },

    // ── Nivel 1 (originales) ────────────────────────────────────────────────
    { name: 'juegos',   type: 'gltfModel', path: '/models/world 1/juegos.glb' },
    { name: 'model1',   type: 'gltfModel', path: '/models/world 1/model1.glb' },
    { name: 'model2',   type: 'gltfModel', path: '/models/world 1/model2.glb' },
    { name: 'model3',   type: 'gltfModel', path: '/models/world 1/model3.glb' },
    { name: 'model4',   type: 'gltfModel', path: '/models/world 1/model4.glb' },
    { name: 'model5',   type: 'gltfModel', path: '/models/world 1/model5.glb' },
    { name: 'model6',   type: 'gltfModel', path: '/models/world 1/model6.glb' },
    { name: 'model7',   type: 'gltfModel', path: '/models/world 1/model7.glb' },
    { name: 'model8',   type: 'gltfModel', path: '/models/world 1/model8.glb' },
    { name: 'model9',   type: 'gltfModel', path: '/models/world 1/model9.glb' },
    { name: 'model10',  type: 'gltfModel', path: '/models/world 1/model10.glb' },
    { name: 'model11',  type: 'gltfModel', path: '/models/world 1/model11.glb' },
    { name: 'model12',  type: 'gltfModel', path: '/models/world 1/model12.glb' },
    { name: 'model13',  type: 'gltfModel', path: '/models/world 1/model13.glb' },
    { name: 'model14',  type: 'gltfModel', path: '/models/world 1/model14.glb' },
    { name: 'model15',  type: 'gltfModel', path: '/models/world 1/model15.glb' },
    { name: 'model16',  type: 'gltfModel', path: '/models/world 1/model16.glb' },
    { name: 'model17',  type: 'gltfModel', path: '/models/world 1/model17.glb' },

    // ── Nivel 1 (exportados desde Blender con _lev1) ────────────────────────
    { name: 'juegos_lev1',          type: 'gltfModel', path: '/models/world 1/juegos_lev1.glb' },
    { name: 'model1_lev1',          type: 'gltfModel', path: '/models/world 1/model1_lev1.glb' },
    { name: 'model2_lev1',          type: 'gltfModel', path: '/models/world 1/model2_lev1.glb' },
    { name: 'model3_lev1',          type: 'gltfModel', path: '/models/world 1/model3_lev1.glb' },
    { name: 'model4_lev1',          type: 'gltfModel', path: '/models/world 1/model4_lev1.glb' },
    { name: 'model5_lev1',          type: 'gltfModel', path: '/models/world 1/model5_lev1.glb' },
    { name: 'model6_lev1',          type: 'gltfModel', path: '/models/world 1/model6_lev1.glb' },
    { name: 'model8_lev1',          type: 'gltfModel', path: '/models/world 1/model8_lev1.glb' },
    { name: 'model9_lev1',          type: 'gltfModel', path: '/models/world 1/model9_lev1.glb' },
    { name: 'model10_lev1',         type: 'gltfModel', path: '/models/world 1/model10_lev1.glb' },
    { name: 'model11_lev1',         type: 'gltfModel', path: '/models/world 1/model11_lev1.glb' },
    { name: 'model12_lev1',         type: 'gltfModel', path: '/models/world 1/model12_lev1.glb' },
    { name: 'model13_lev1',         type: 'gltfModel', path: '/models/world 1/model13_lev1.glb' },
    { name: 'model14_lev1',         type: 'gltfModel', path: '/models/world 1/model14_lev1.glb' },
    { name: 'model15_lev1',         type: 'gltfModel', path: '/models/world 1/model15_lev1.glb' },
    { name: 'model16_lev1',         type: 'gltfModel', path: '/models/world 1/model16_lev1.glb' },
    { name: 'model17_lev1',         type: 'gltfModel', path: '/models/world 1/model17_lev1.glb' },
    { name: 'mesa_lev1',            type: 'gltfModel', path: '/models/world 1/mesa_lev1.glb' },
    { name: 'caja_lev1',            type: 'gltfModel', path: '/models/world 1/caja_lev1.glb' },
    { name: 'rootnode.015_lev1',    type: 'gltfModel', path: '/models/world 1/rootnode.015_lev1.glb' },
    { name: 'tent_lev1',           type: 'gltfModel', path: '/models/world 1/tent_lev1.glb' },
    { name: 'tent1_lev1',          type: 'gltfModel', path: '/models/world 1/tent1_lev1.glb' },
    { name: 'tentgrande_lev1',     type: 'gltfModel', path: '/models/world 1/tentgrande_lev1.glb' },
    { name: 'rueda_lev1',          type: 'gltfModel', path: '/models/world 1/rueda_lev1.glb' },
    { name: 'circusbaby_lev1',     type: 'gltfModel', path: '/models/world 1/circusbaby_lev1.glb' },
    { name: 'props_lev1',          type: 'gltfModel', path: '/models/world 1/props_lev1.glb' },
    { name: 'props2_lev1',         type: 'gltfModel', path: '/models/world 1/props2_lev1.glb' },
    { name: 'basura_lev1',         type: 'gltfModel', path: '/models/world 1/basura_lev1.glb' },
    { name: 'carrito_lev1',        type: 'gltfModel', path: '/models/world 1/carrito_lev1.glb' },
    { name: 'car_lev1',            type: 'gltfModel', path: '/models/world 1/car_lev1.glb' },
    { name: 'coin_lev1',           type: 'gltfModel', path: '/models/world 1/coin_lev1.glb' },
    { name: 'coin2_lev1',          type: 'gltfModel', path: '/models/world 1/coin2_lev1.glb' },
    { name: 'coin3_lev1',          type: 'gltfModel', path: '/models/world 1/coin3_lev1.glb' },
    { name: 'coin4_lev1',          type: 'gltfModel', path: '/models/world 1/coin4_lev1.glb' },
    { name: 'coin5_lev1',          type: 'gltfModel', path: '/models/world 1/coin5_lev1.glb' },
    { name: 'coin6_lev1',          type: 'gltfModel', path: '/models/world 1/coin6_lev1.glb' },
    { name: 'coin7_lev1',          type: 'gltfModel', path: '/models/world 1/coin7_lev1.glb' },
    { name: 'coin8_lev1',          type: 'gltfModel', path: '/models/world 1/coin8_lev1.glb' },
    { name: 'coin9_lev1',          type: 'gltfModel', path: '/models/world 1/coin9_lev1.glb' },
    { name: 'coin10_lev1',         type: 'gltfModel', path: '/models/world 1/coin10_lev1.glb' },

    // ── Nivel 2 (originales) ────────────────────────────────────────────────
    { name: 'ancient_building',   type: 'gltfModel', path: '/models/world 2/ancient_building.glb' },
    { name: 'desert_stone_house', type: 'gltfModel', path: '/models/world 2/desert_stone_house.glb' },
    { name: 'fantasy_house',      type: 'gltfModel', path: '/models/world 2/fantasy_house.glb' },
    { name: 'old_castle',         type: 'gltfModel', path: '/models/world 2/old_castle.glb' },
    { name: 'old_castle_1',       type: 'gltfModel', path: '/models/world 2/old_castle_1.glb' },
    { name: 'old_house',          type: 'gltfModel', path: '/models/world 2/old_house.glb' },
    { name: 'old_house_1',        type: 'gltfModel', path: '/models/world 2/old_house_1.glb' },
    { name: 'stone_building',     type: 'gltfModel', path: '/models/world 2/stone_building.glb' },

    // ── Nivel 2 (exportados desde Blender con _lev2) ────────────────────────
    { name: 'storageh_lev2',          type: 'gltfModel', path: '/models/world 2/storageh_lev2.glb' },
    { name: 'p2_lev2',                type: 'gltfModel', path: '/models/world 2/p2_lev2.glb' },
    { name: 'p3_lev2',                type: 'gltfModel', path: '/models/world 2/p3_lev2.glb' },
    { name: 'p4_lev2',                type: 'gltfModel', path: '/models/world 2/p4_lev2.glb' },
    { name: 'p5_lev2',                type: 'gltfModel', path: '/models/world 2/p5_lev2.glb' },
    { name: 'p6_lev2',                type: 'gltfModel', path: '/models/world 2/p6_lev2.glb' },
    { name: 'fantasy_house_lev2',     type: 'gltfModel', path: '/models/world 2/fantasy_house_lev2.glb' },
    { name: 'old_house_lev2',         type: 'gltfModel', path: '/models/world 2/old_house_lev2.glb' },
    { name: 'stairscorner_lev2',      type: 'gltfModel', path: '/models/world 2/stairscorner_lev2.glb' },
    { name: 'floor_lev2',             type: 'gltfModel', path: '/models/world 2/floor_lev2.glb' },
    { name: 'floor2_lev2',            type: 'gltfModel', path: '/models/world 2/floor2_lev2.glb' },
    { name: 'floor3_lev2',            type: 'gltfModel', path: '/models/world 2/floor3_lev2.glb' },
    { name: 'floor4_lev2',            type: 'gltfModel', path: '/models/world 2/floor4_lev2.glb' },
    { name: 'floor5_lev2',            type: 'gltfModel', path: '/models/world 2/floor5_lev2.glb' },
    { name: 'floor6_lev2',            type: 'gltfModel', path: '/models/world 2/floor6_lev2.glb' },
    { name: 'wallrocks_lev2',         type: 'gltfModel', path: '/models/world 2/wallrocks_lev2.glb' },
    { name: 'castle_lev2',            type: 'gltfModel', path: '/models/world 2/castle_lev2.glb' },
    { name: 'desert_stone_house_lev2',type: 'gltfModel', path: '/models/world 2/desert_stone_house_lev2.glb' },
    { name: 'fuerte_lev2',            type: 'gltfModel', path: '/models/world 2/fuerte_lev2.glb' },
    { name: 'rock_lev2',              type: 'gltfModel', path: '/models/world 2/rock_lev2.glb' },
    { name: 'rock2_lev2',             type: 'gltfModel', path: '/models/world 2/rock2_lev2.glb' },
    { name: 'rock3_lev2',             type: 'gltfModel', path: '/models/world 2/rock3_lev2.glb' },
    { name: 'rock4_lev2',             type: 'gltfModel', path: '/models/world 2/rock4_lev2.glb' },
    { name: 'ancient_building_lev2',  type: 'gltfModel', path: '/models/world 2/ancient_building_lev2.glb' },
    { name: 'old_castle_lev2',        type: 'gltfModel', path: '/models/world 2/old_castle_lev2.glb' },
    { name: 'old_castle_1_lev2',      type: 'gltfModel', path: '/models/world 2/old_castle_1_lev2.glb' },
    { name: 'old_castle_1.002_lev2',   type: 'gltfModel', path: '/models/world 2/old_castle_1.002_lev2.glb' },
    { name: 'object_4.015_lev2',       type: 'gltfModel', path: '/models/world 2/object_4.015_lev2.glb' },
    { name: 'old_house_1_lev2',       type: 'gltfModel', path: '/models/world 2/old_house_1_lev2.glb' },
    { name: 'stone_building_lev2',    type: 'gltfModel', path: '/models/world 2/stone_building_lev2.glb' },
    { name: 'pared_lev2',             type: 'gltfModel', path: '/models/world 2/pared_lev2.glb' },
    { name: 'farm_lev2',              type: 'gltfModel', path: '/models/world 2/farm_lev2.glb' },

    // ── Nivel 3 ─────────────────────────────────────────────────────────────
    { name: 'barracks_firstage_level2',   type: 'gltfModel', path: '/models/world 3/barracks_firstage_level2.glb' },
    { name: 'bell_tower',                 type: 'gltfModel', path: '/models/world 3/bell_tower.glb' },
    { name: 'houses_firstage_1_level3',   type: 'gltfModel', path: '/models/world 3/houses_firstage_1_level3.glb' },
    { name: 'houses_secondage_1_level3',  type: 'gltfModel', path: '/models/world 3/houses_secondage_1_level3.glb' },
    { name: 'marketstand_1',              type: 'gltfModel', path: '/models/world 3/marketstand_1.glb' },
    { name: 'mine',                       type: 'gltfModel', path: '/models/world 3/mine.glb' },
    { name: 'watchtower_secondage_level3',type: 'gltfModel', path: '/models/world 3/watchtower_secondage_level3.glb' },
    { name: 'windmill_secondage',         type: 'gltfModel', path: '/models/world 3/windmill_secondage.glb' },
    { name: 'city_lev3',                  type: 'gltfModel', path: '/models/world 3/city_lev3.glb' },
    { name: 'barrio_lev3',                type: 'gltfModel', path: '/models/world 3/barrio_lev3.glb' },
    { name: 'road_lev3',                  type: 'gltfModel', path: '/models/world 3/road_lev3.glb' },
    { name: 'road2_lev3',                 type: 'gltfModel', path: '/models/world 3/road2_lev3.glb' },
    { name: 'road2x_lev3',                type: 'gltfModel', path: '/models/world 3/road2x_lev3.glb' },
    { name: 'road3_lev3',                 type: 'gltfModel', path: '/models/world 3/road3_lev3.glb' },
    { name: 'road4_lev3',                 type: 'gltfModel', path: '/models/world 3/road4_lev3.glb' },
    { name: 'road5_lev3',                 type: 'gltfModel', path: '/models/world 3/road5_lev3.glb' },
    { name: 'road6_lev3',                 type: 'gltfModel', path: '/models/world 3/road6_lev3.glb' },
    { name: 'road7_lev3',                 type: 'gltfModel', path: '/models/world 3/road7_lev3.glb' },
    { name: 'road8_lev3',                 type: 'gltfModel', path: '/models/world 3/road8_lev3.glb' },
    { name: 'road9_lev3',                 type: 'gltfModel', path: '/models/world 3/road9_lev3.glb' },
    { name: 'road10_lev3',                type: 'gltfModel', path: '/models/world 3/road10_lev3.glb' },
    { name: 'road12_lev3',                type: 'gltfModel', path: '/models/world 3/road12_lev3.glb' },
    { name: 'road13_lev3',                type: 'gltfModel', path: '/models/world 3/road13_lev3.glb' },
    { name: 'road14_lev3',                type: 'gltfModel', path: '/models/world 3/road14_lev3.glb' },
    { name: 'road15_lev3',                type: 'gltfModel', path: '/models/world 3/road15_lev3.glb' },
    { name: 'road16_lev3',                type: 'gltfModel', path: '/models/world 3/road16_lev3.glb' },
    { name: 'road17_lev3',                type: 'gltfModel', path: '/models/world 3/road17_lev3.glb' },
    { name: 'road18_lev3',                type: 'gltfModel', path: '/models/world 3/road18_lev3.glb' },
    { name: 'road19_lev3',                type: 'gltfModel', path: '/models/world 3/road19_lev3.glb' },
    { name: 'road20_lev3',                type: 'gltfModel', path: '/models/world 3/road20_lev3.glb' },
    { name: 'road21_lev3',                type: 'gltfModel', path: '/models/world 3/road21_lev3.glb' },
    { name: 'road22_lev3',                type: 'gltfModel', path: '/models/world 3/road22_lev3.glb' },
    { name: 'road22.001_lev3',            type: 'gltfModel', path: '/models/world 3/road22.001_lev3.glb' },
    { name: 'road22.002_lev3',            type: 'gltfModel', path: '/models/world 3/road22.002_lev3.glb' },
    { name: 'road22x1_lev3',              type: 'gltfModel', path: '/models/world 3/road22x1_lev3.glb' },
    { name: 'road25_lev3',                type: 'gltfModel', path: '/models/world 3/road25_lev3.glb' },
    { name: 'roadcorner_lev3',            type: 'gltfModel', path: '/models/world 3/roadcorner_lev3.glb' },
    { name: 'roadcorner.001_lev3',        type: 'gltfModel', path: '/models/world 3/roadcorner.001_lev3.glb' },
    { name: 'roadcorner2_lev3',           type: 'gltfModel', path: '/models/world 3/roadcorner2_lev3.glb' },
    { name: 'roadq_lev3',                 type: 'gltfModel', path: '/models/world 3/roadq_lev3.glb' },
    { name: 'road19x1_lev3',              type: 'gltfModel', path: '/models/world 3/road19x1_lev3.glb' },
    { name: 'road20x2_lev3',              type: 'gltfModel', path: '/models/world 3/road20x2_lev3.glb' },
    { name: 'road21x2_lev3',              type: 'gltfModel', path: '/models/world 3/road21x2_lev3.glb' },
    { name: 'road22x2_lev3',              type: 'gltfModel', path: '/models/world 3/road22x2_lev3.glb' },
    { name: 'almacen_lev3',               type: 'gltfModel', path: '/models/world 3/almacen_lev3.glb' },
    { name: 'almacen2_lev3',              type: 'gltfModel', path: '/models/world 3/almacen2_lev3.glb' },
    { name: 'fabrica_lev3',               type: 'gltfModel', path: '/models/world 3/fabrica_lev3.glb' },
    { name: 'fabrica2_lev3',              type: 'gltfModel', path: '/models/world 3/fabrica2_lev3.glb' },
    { name: 'park_lev3',                  type: 'gltfModel', path: '/models/world 3/park_lev3.glb' },
    { name: 'coin_lev3',                  type: 'gltfModel', path: '/models/world 3/coin_lev3.glb' },
    { name: 'coin2_lev3',                 type: 'gltfModel', path: '/models/world 3/coin2_lev3.glb' },
    { name: 'coin3_lev3',                 type: 'gltfModel', path: '/models/world 3/coin3_lev3.glb' },
    { name: 'coin4_lev3',                 type: 'gltfModel', path: '/models/world 3/coin4_lev3.glb' },
    { name: 'coin5_lev3',                 type: 'gltfModel', path: '/models/world 3/coin5_lev3.glb' },
    { name: 'coin6_lev3',                 type: 'gltfModel', path: '/models/world 3/coin6_lev3.glb' },
    { name: 'coin7_lev3',                 type: 'gltfModel', path: '/models/world 3/coin7_lev3.glb' },
    { name: 'coin8_lev3',                 type: 'gltfModel', path: '/models/world 3/coin8_lev3.glb' },
    { name: 'coin9_lev3',                 type: 'gltfModel', path: '/models/world 3/coin9_lev3.glb' },
    { name: 'coin10_lev3',                type: 'gltfModel', path: '/models/world 3/coin10_lev3.glb' },

    // ── Nivel 4 (originales) ────────────────────────────────────────────────
    { name: 'suelo_4', type: 'gltfModel', path: '/models/world 4/suelo_nivel4.glb' },
    { name: 'arbol_4', type: 'gltfModel', path: '/models/world 4/arbol_nivel4.glb' },
    { name: 'Pawn',    type: 'gltfModel', path: '/models/world 4/Pawn.glb' },

    // ── Nivel 4 (exportados desde Blender con _lev4) ────────────────────────
    { name: 'suelo_nivel4_lev4',            type: 'gltfModel', path: '/models/world 4/suelo_nivel4_lev4.glb' },
    { name: 'suelo_nivel42_lev4',           type: 'gltfModel', path: '/models/world 4/suelo_nivel42_lev4.glb' },
    { name: 'suelo_nivel43_lev4',           type: 'gltfModel', path: '/models/world 4/suelo_nivel43_lev4.glb' },
    { name: 'suelo_nivel45_lev4',           type: 'gltfModel', path: '/models/world 4/suelo_nivel45_lev4.glb' },
    { name: 'arbol_nivel4_lev4',            type: 'gltfModel', path: '/models/world 4/arbol_nivel4_lev4.glb' },
    { name: 'arbol_nivel42_lev4',           type: 'gltfModel', path: '/models/world 4/arbol_nivel42_lev4.glb' },
    { name: 'arbol_nivel43_lev4',           type: 'gltfModel', path: '/models/world 4/arbol_nivel43_lev4.glb' },
    { name: 'arbol_nivel44_lev4',           type: 'gltfModel', path: '/models/world 4/arbol_nivel44_lev4.glb' },
    { name: 'arbol_nivel45_lev4',           type: 'gltfModel', path: '/models/world 4/arbol_nivel45_lev4.glb' },
    { name: 'pawn_lev4',                    type: 'gltfModel', path: '/models/world 4/pawn_lev4.glb' },
    { name: 'pawn1_lev4',                   type: 'gltfModel', path: '/models/world 4/pawn1_lev4.glb' },
    { name: 'pawn2_lev4',                   type: 'gltfModel', path: '/models/world 4/pawn2_lev4.glb' },
    { name: 'pawn3_lev4',                   type: 'gltfModel', path: '/models/world 4/pawn3_lev4.glb' },
    { name: 'pawn4_lev4',                   type: 'gltfModel', path: '/models/world 4/pawn4_lev4.glb' },
    { name: 'pawn5_lev4',                   type: 'gltfModel', path: '/models/world 4/pawn5_lev4.glb' },
    { name: 'root_lev4',                    type: 'gltfModel', path: '/models/world 4/root_lev4.glb' },
    { name: 'low_poly_chess_knights_lev4',  type: 'gltfModel', path: '/models/world 4/low_poly_chess_knights_lev4.glb' },
    { name: 'low_poly_chess_knights2_lev4', type: 'gltfModel', path: '/models/world 4/low_poly_chess_knights2_lev4.glb' },
    { name: 'low_poly_chess_knights3_lev4', type: 'gltfModel', path: '/models/world 4/low_poly_chess_knights3_lev4.glb' },
    { name: 'low_poly_chess_knights4_lev4', type: 'gltfModel', path: '/models/world 4/low_poly_chess_knights4_lev4.glb' },
    { name: 'low_poly_chess_knights5_lev4', type: 'gltfModel', path: '/models/world 4/low_poly_chess_knights5_lev4.glb' },
    { name: 'alfombra_lev4',               type: 'gltfModel', path: '/models/world 4/alfombra_lev4.glb' },
    { name: 'livingroom_lev4',             type: 'gltfModel', path: '/models/world 4/livingroom_lev4.glb' },

    // ── Nivel 5 ─────────────────────────────────────────────────────────────
    { name: 'modelo_mundo_5',                  type: 'gltfModel', path: '/models/world 5/suelo_nivel5.glb' },
    { name: 'arbol_mundo5',                    type: 'gltfModel', path: '/models/world 5/arbol mundo5.glb' },
    { name: 'snow1_lev5',                          type: 'gltfModel', path: '/models/world 5/snow1_lev5.glb' },
    { name: 'snow2_lev5',                          type: 'gltfModel', path: '/models/world 5/snow2_lev5.glb' },
    { name: 'snow3_lev5',                          type: 'gltfModel', path: '/models/world 5/snow3_lev5.glb' },
    { name: 'housesnow_lev5',                      type: 'gltfModel', path: '/models/world 5/housesnow_lev5.glb' },
    { name: 'housesnowrfr_lev5',                   type: 'gltfModel', path: '/models/world 5/housesnowrfr_lev5.glb' },
    { name: 'housesnowroja_lev5',                  type: 'gltfModel', path: '/models/world 5/housesnowroja_lev5.glb' },
    { name: 'housesnowroja2_lev5',                 type: 'gltfModel', path: '/models/world 5/housesnowroja2_lev5.glb' },
    { name: 'casasnow_lev5',                       type: 'gltfModel', path: '/models/world 5/casasnow_lev5.glb' },
    { name: 'casasnow2_lev5',                      type: 'gltfModel', path: '/models/world 5/casasnow2_lev5.glb' },
    { name: 'casaverde_lev5',                      type: 'gltfModel', path: '/models/world 5/casaverde_lev5.glb' },
    { name: 'casaverde2_lev5',                     type: 'gltfModel', path: '/models/world 5/casaverde2_lev5.glb' },
    { name: 'casacompleta_lev5',                   type: 'gltfModel', path: '/models/world 5/casacompleta_lev5.glb' },
    { name: 'casaconjunto_lev5',                   type: 'gltfModel', path: '/models/world 5/casaconjunto_lev5.glb' },
    { name: 'church_lev5',                         type: 'gltfModel', path: '/models/world 5/church_lev5.glb' },
    { name: 'tiendas_lev5',                        type: 'gltfModel', path: '/models/world 5/tiendas_lev5.glb' },
    { name: 'tiendas2_lev5',                       type: 'gltfModel', path: '/models/world 5/tiendas2_lev5.glb' },
    { name: 'montanas_lev5',                       type: 'gltfModel', path: '/models/world 5/montanas_lev5.glb' },
    { name: 'montanas2_lev5',                      type: 'gltfModel', path: '/models/world 5/montanas2_lev5.glb' },
    { name: 'tree_lev5',                           type: 'gltfModel', path: '/models/world 5/tree_lev5.glb' },
    { name: 'tre1_lev5',                           type: 'gltfModel', path: '/models/world 5/tre1_lev5.glb' },
    { name: 'tre2_lev5',                           type: 'gltfModel', path: '/models/world 5/tre2_lev5.glb' },
    { name: 'tree3_lev5',                          type: 'gltfModel', path: '/models/world 5/tree3_lev5.glb' },
    { name: 'tree4_lev5',                          type: 'gltfModel', path: '/models/world 5/tree4_lev5.glb' },
    { name: 'tree5_lev5',                          type: 'gltfModel', path: '/models/world 5/tree5_lev5.glb' },
    { name: 'tree6_lev5',                          type: 'gltfModel', path: '/models/world 5/tree6_lev5.glb' },
    { name: 'tree62_lev5',                         type: 'gltfModel', path: '/models/world 5/tree62_lev5.glb' },
    { name: 'tree63_lev5',                         type: 'gltfModel', path: '/models/world 5/tree63_lev5.glb' },
    { name: 'tree64_lev5',                         type: 'gltfModel', path: '/models/world 5/tree64_lev5.glb' },
    { name: 'tree65_lev5',                         type: 'gltfModel', path: '/models/world 5/tree65_lev5.glb' },
    { name: 'tree7_lev5',                          type: 'gltfModel', path: '/models/world 5/tree7_lev5.glb' },
    { name: 'deathtree_lev5',                      type: 'gltfModel', path: '/models/world 5/deathtree_lev5.glb' },
    { name: 'deathtree2_lev5',                     type: 'gltfModel', path: '/models/world 5/deathtree2_lev5.glb' },
    { name: 'deathtree3_lev5',                     type: 'gltfModel', path: '/models/world 5/deathtree3_lev5.glb' },
    { name: 'deathtreemountain_lev5',              type: 'gltfModel', path: '/models/world 5/deathtreemountain_lev5.glb' },
    { name: 'deathtreemountain2_lev5',             type: 'gltfModel', path: '/models/world 5/deathtreemountain2_lev5.glb' },
    { name: 'deathtreemountain3_lev5',             type: 'gltfModel', path: '/models/world 5/deathtreemountain3_lev5.glb' },
    { name: 'deathtreemountain4_lev5',             type: 'gltfModel', path: '/models/world 5/deathtreemountain4_lev5.glb' },
    { name: 'deathtreemountain5_lev5',             type: 'gltfModel', path: '/models/world 5/deathtreemountain5_lev5.glb' },
    { name: 'dmuñecodenieve_lev5',                 type: 'gltfModel', path: '/models/world 5/dmuñecodenieve_lev5.glb' },
    { name: 'dmuñecodenievemontaña_lev5',          type: 'gltfModel', path: '/models/world 5/dmuñecodenievemontaña_lev5.glb' },
    { name: 'dmuñecodenievemontaña2_lev5',         type: 'gltfModel', path: '/models/world 5/dmuñecodenievemontaña2_lev5.glb' },
    { name: 'coin_lev5',                           type: 'gltfModel', path: '/models/world 5/coin_lev5.glb' },
    { name: 'coin2_lev5',                          type: 'gltfModel', path: '/models/world 5/coin2_lev5.glb' },
    { name: 'coin3_lev5',                          type: 'gltfModel', path: '/models/world 5/coin3_lev5.glb' },
    { name: 'coin4_lev5',                          type: 'gltfModel', path: '/models/world 5/coin4_lev5.glb' },
    { name: 'coin5_lev5',                          type: 'gltfModel', path: '/models/world 5/coin5_lev5.glb' },
    { name: 'coin6_lev5',                          type: 'gltfModel', path: '/models/world 5/coin6_lev5.glb' },
    { name: 'coin7_lev5',                          type: 'gltfModel', path: '/models/world 5/coin7_lev5.glb' },
    { name: 'coin8_lev5',                          type: 'gltfModel', path: '/models/world 5/coin8_lev5.glb' },
    { name: 'coin9_lev5',                          type: 'gltfModel', path: '/models/world 5/coin9_lev5.glb' },
    { name: 'coin10_lev5',                         type: 'gltfModel', path: '/models/world 5/coin10_lev5.glb' },
    { name: 'empty_lev5',                          type: 'gltfModel', path: '/models/world 5/empty_lev5.glb' },
    { name: 'group1213442301.001_lev5',            type: 'gltfModel', path: '/models/world 5/group1213442301.001_lev5.glb' }
]